export const TotalData = [
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
    {
        organization: 'Организация',
        date: 'Дата бронирования',
        item: 'Пробор',
        analyze: ['Анализ'],
        executor: 'Оператор',
        sample: 1,
    },
]

export const EmployeesData = [
    {
        executor: 'Оператор',
        monday: 'Прибор с длинным названием1',
        tuesday: 'Прибор',
        wednesday: 'Прибор',
        thursday: 'Прибор',
        friday: 'Прибор',
        saturday: 'Прибор',
        sunday: 'Прибор'
    },
    {
        executor: 'Оператор',
        monday: 'Прибор с длинным названием1',
        tuesday: 'Прибор',
        wednesday: 'Прибор',
        friday: 'Прибор',
        saturday: 'Прибор',
        sunday: 'Прибор'
    },
    {
        executor: 'Оператор',
        monday: 'Прибор с длинным названием1',
        tuesday: 'Прибор',
        wednesday: 'Прибор',
        thursday: 'Прибор',
        saturday: 'Прибор',
        sunday: 'Прибор'
    },
    {
        executor: 'Оператор',
        monday: 'Прибор с длинным названием1',
        tuesday: 'Прибор',
        wednesday: 'Прибор',
        thursday: 'Прибор',
        saturday: 'Прибор',
        sunday: 'Прибор'
    },
    {
        executor: 'Оператор',
        monday: 'Прибор с длинным названием1',
        tuesday: 'Прибор',
        wednesday: 'Прибор',
        friday: 'Прибор',
        saturday: 'Прибор',
        sunday: 'Прибор'
    },
    {
        executor: 'Оператор',
        monday: 'Прибор с длинным названием1',
        tuesday: 'Прибор',
        wednesday: 'Прибор',
        friday: 'Прибор',
        saturday: 'Прибор',
        sunday: 'Прибор'
    },
    {
        executor: 'Оператор',
        monday: 'Прибор с длинным названием1',
        tuesday: 'Прибор',
        wednesday: 'Прибор',
        friday: 'Прибор',
        saturday: 'Прибор',
        sunday: 'Прибор'
    },
    {
        executor: 'Оператор',
        monday: 'Прибор с длинным названием1',
        tuesday: 'Прибор',
        wednesday: 'Прибор',
        friday: 'Прибор',
        saturday: 'Прибор',
        sunday: 'Прибор'
    },
    {
        executor: 'Оператор',
        monday: 'Прибор с длинным названием1',
        tuesday: 'Прибор',
        wednesday: 'Прибор',
        thursday: 'Прибор',
        friday: 'Прибор',
        sunday: 'Прибор'
    },
    {
        executor: 'Оператор',
        monday: 'Прибор с длинным названием1',
        tuesday: 'Прибор',
        wednesday: 'Прибор',
        thursday: 'Прибор',
        friday: 'Прибор',
        sunday: 'Прибор'
    },
    {
        executor: 'Оператор',
        monday: 'Прибор с длинным названием1',
        tuesday: 'Прибор',
        wednesday: 'Прибор',
        thursday: 'Прибор',
        friday: 'Прибор',
        saturday: 'Прибор',
        sunday: 'Прибор'
    },
    {
        executor: 'Оператор',
        monday: 'Прибор с длинным названием1',
        tuesday: 'Прибор',
        wednesday: 'Прибор',
        thursday: 'Прибор',
        friday: 'Прибор',
        saturday: 'Прибор',
        sunday: 'Прибор'
    },
    {
        executor: 'Оператор',
        monday: 'Прибор с длинным названием1',
        tuesday: 'Прибор',
        wednesday: 'Прибор',
        thursday: 'Прибор',
        friday: 'Прибор',
        saturday: 'Прибор',
        sunday: 'Прибор'
    },
]

export const InstrumentsData = [
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
        sunday: ['сломан']
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
        sunday: ['сломан']
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
        sunday: ['сломан']
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
        sunday: ['сломан']
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
        sunday: ['сломан']
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
        sunday: ['сломан']
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
        sunday: ['сломан']
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
        sunday: ['сломан']
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
        sunday: ['сломан']
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
        sunday: ['сломан']
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
        sunday: ['сломан']
    },
    {
        item: 'Прибор',
        monday: ['Анализ', 'Анализ2'],
        tuesday: ['Анализ', 'Анализ2'],
        wednesday: ['Анализ', 'Анализ2'],
        thursday: ['Анализ', 'Анализ2'],
        friday: ['Анализ', 'Анализ2'],
        saturday: ['Анализ', 'Анализ2'],
        sunday: ['сломан']
    },
]

