FROM python:3.9-alpine

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev postgresql-client

COPY requirements.txt ./
RUN pip3 install --upgrade pip
RUN pip3 install --no-cache-dir -r requirements.txt

COPY entrypoint_2.sh .
RUN sed -i 's/\r$//g' /app/entrypoint_2.sh
RUN chmod +x /app/entrypoint_2.sh

COPY . .

ENTRYPOINT ["sh", "/app/entrypoint_2.sh"]