SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE TABLE IF NOT EXISTS public.projects_booking (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	project_id uuid NOT NULL,
	date_booking date NOT NULL,
	analyse_id uuid NOT NULL,
	equipment_id uuid NOT NULL,
	executor_id uuid NOT NULL,
	count_analyses int4 NOT NULL,
	status varchar(254) NOT NULL,
	is_delete bool NULL,
	"comment" text NULL,
	CONSTRAINT projects_booking_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.block_booking (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE),
	project_id uuid NOT NULL,
	date_booking date NULL,
	analyse_id uuid NULL,
	equipment_id uuid NULL,
	executor_id uuid NULL,
	is_block bool NULL,
	write_timestamp timestamp NOT NULL DEFAULT now(),
	cookies_key uuid NOT NULL DEFAULT gen_random_uuid(),
	update_timestamp timestamp NULL,
	id_delete bool NULL DEFAULT false,
	CONSTRAINT block_booking_id PRIMARY KEY (id)
);